server:
  port: ${CLOUDDRIVER_PORT:7002}
  address: $CLOUDDRIVER_HOST

services:
  front50:
    baseUrl: http://$FRONT50_HOST:$FRONT50_PORT

redis:
  connection: redis://$REDIS_HOST:6379

aws:
  enabled: ${AWS_ENABLED:false}

google:
  enabled: ${GOOGLE_ENABLED:false}

  kmsServer: http://$KMS_HOST:$KMS_PORT
  accounts:
    $GOOGLE_CREDENTIALS_DECLARATION

