server:
  port: ${FRONT50_PORT:8080}
  address: $FRONT50_HOST

cassandra:
  embedded: false
  host: $CASSANDRA_HOST

aws:
  simpleDBEnabled: false
  defaultSimpleDBDomain: CLOUD_APPLICATIONS

spinnaker:
  cassandra:
    enabled: true
    host: $CASSANDRA_HOST
    port: 9042
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: global
