server:
  port: ${ORCA_PORT:8083}
  address: $ORCA_HOST

oort:
  baseUrl: http://$OORT_HOST:$OORT_PORT
front50:
  baseUrl: http://$FRONT50_HOST:$FRONT50_PORT
mort:
  baseUrl: http://$MORT_HOST:$MORT_PORT
kato:
  baseUrl: http://$KATO_HOST:$KATO_PORT
rush:
  baseUrl: http://$RUSH_HOST:$RUSH_PORT
bakery:
  baseUrl: http://$BAKERY_HOST:$BAKERY_PORT
  extractBuildDetails: true
  propagateCloudProviderType: true
echo:
  baseUrl: http://$ECHO_HOST:$ECHO_PORT
igor:
  baseUrl: http://$IGOR_HOST:$IGOR_PORT

# TODO(duftler): Remove this once flex is conditionally-enabled in orca.
flex:
  baseUrl: http://not-a-host

default:
  bake:
    account: default
  securityGroups:
  vpc:
    securityGroups:

redis:
  connection: redis://$REDIS_HOST:$REDIS_PORT

