server:
  port: ${RUSH_PORT:8085}
  address: $RUSH_HOST

cassandra:
  embedded: false
  host: $CASSANDRA_HOST

docker:
  accounts:
    - name: $GOOGLE_PRIMARY_ACCOUNT_NAME
      url: http://$DOCKER_ADDRESS
      registry: http://$DOCKER_REGISTRY_HOST:$DOCKER_REGISTRY_PORT
