server:
  port: ${ECHO_PORT:8089}
  address: $ECHO_HOST

cassandra:
  embedded: false
  host: $CASSANDRA_HOST

front50:
  baseUrl: http://$FRONT50_HOST:$FRONT50_PORT

orca:
  baseUrl: http://$ORCA_HOST:$ORCA_PORT
  enabled: true

endpoints.health.sensitive: false
