server:
  port: 8089

cassandra:
  embedded: false
  host: $CASSANDRA_HOST

front50:
  baseUrl: http://localhost:8080

orca:
  baseUrl: http://localhost:8083
  enabled: true

endpoints.health.sensitive: false
