server:
  port: ${GATE_PORT:8084}
  address: $GATE_HOST

services:
  oort:
    baseUrl: http://$OORT_HOST:$OORT_PORT
  orca:
    baseUrl: http://$ORCA_HOST:$ORCA_PORT
  front50:
    baseUrl: http://$FRONT50_HOST:$FRONT50_PORT
  mort:
    baseUrl: http://$MORT_HOST:$MORT_PORT
  kato:
    baseUrl: http://$KATO_HOST:$KATO_PORT
#optional services:
  echo:
    enabled: true
    baseUrl: http://$ECHO_HOST:$ECHO_PORT
  flapjack:
    enabled: false
  igor:
    enabled: ${IGOR_ENABLED:false}
    baseUrl: http://$IGOR_HOST:$IGOR_PORT

redis:
  connection: redis://$REDIS_HOST:$REDIS_PORT

