server:
  port: 8084

services:
  oort:
    baseUrl: http://localhost:7002
  orca:
    baseUrl: http://localhost:8083
  front50:
    baseUrl: http://localhost:8080
  mort:
    baseUrl: http://localhost:7002
  kato:
    baseUrl: http://localhost:7002
#optional services:
  echo:
    enabled: true
    baseUrl: http://localhost:8089
  flapjack:
    enabled: false
  igor:
    enabled: ${IGOR_ENABLED:false}
    baseUrl: http://localhost:8088

redis:
  connection: redis://$REDIS_HOST:6379      

