server:
  port: ${services.gce_kms.port:7909}
  address: ${services.gce_kms.host:localhost}

credentials:
  accounts:
    - name: ${providers.google.primaryCredentials.name}
      project: ${providers.google.primaryCredentials.project}
      jsonPath: ${providers.google.primaryCredentials.jsonPath}

