server:
  port: ${IGOR_PORT:8088}
  address: $IGOR_HOST

jenkins:
  masters:
    - name: $JENKINS_MASTER_NAME
      address: http://$JENKINS_ADDRESS
      username: $JENKINS_USERNAME
      password: $JENKINS_PASSWORD

services:
  echo:
    baseUrl: http://$ECHO_HOST:$ECHO_PORT
