server:
  port: ${services.igor.port:8088}
  address: ${services.igor.host:localhost}

jenkins:
  masters:
    - name: ${services.jenkins.name}
      address: ${services.jenkins.baseUrl}
      username: ${services.jenkins.username}
      password: ${services.jenkins.password}

# This is recursive
#services:
#  echo:
#    baseUrl: ${services.echo.baseUrl}
