server:
  port: 8087

redis:
  host: $REDIS_HOST

aws:
  enabled: $AWS_ENABLED

docker:
  enabled: $DOCKER_ENABLED

google:
  enabled: $GOOGLE_ENABLED
  gce:
    bakeryDefaults:
      project: $GOOGLE_PRIMARY_MANAGED_PROJECT_ID

rush:
  credentials: $GOOGLE_PRIMARY_ACCOUNT_NAME
