server:
  port: ${services.rosco.port:8087}
  address: ${services.rosco.host:localhost}

redis:
  host: ${services.redis.host:localhost}

aws:
  enabled: ${providers.aws.enabled:false}

docker:
  enabled: ${services.docker.enabled:false}

google:
  enabled: ${providers.google.enabled:false}
  gce:
    bakeryDefaults:
      project: ${providers.google.primaryCredentials.project}

rush:
  credentials: ${services.rush.primaryAccount}
