server:
  port: 8085

cassandra:
  embedded: false
  host: $CASSANDRA_HOST

docker:
  accounts:
    - name: $GOOGLE_PRIMARY_ACCOUNT_NAME
      url: http://$DOCKER_ADDRESS
      registry: http://localhost:5000
