global:
  spinnaker:
    environment: test

services:
  default:
    host: localhost
    protocol: http
    primaryAccountName: service-default-primaryAcountName-not-defined

  clouddriver:
    host: ${services.default.host}
    port: 7002
    baseUrl: ${services.default.protocol}://${services.clouddriver.host}:${services.clouddriver.port}

  echo:
    enabled: true
    host: ${services.default.host}
    port: 8089
    baseUrl: ${services.default.protocol}://${services.echo.host}:${services.echo.port}

  front50:
    host: ${services.default.host}
    port: 8080
    baseUrl: ${services.default.protocol}://${services.front50.host}:${services.front50.port}

  gate:
    host: ${services.default.host}
    port: 8084
    baseUrl: ${services.default.protocol}://${services.gate.host}:${services.gate.port}

  igor:
    enabled: false
    host: ${services.default.host}
    port: 8088
    baseUrl: ${services.default.protocol}://${services.igor.host}:${services.igor.port}

  kato:
    host: ${services.clouddriver.host}
    port: ${services.clouddriver.port}
    baseUrl: ${services.clouddriver.baseUrl}

  mort:
    host: ${services.clouddriver.host}
    port: ${services.clouddriver.port}
    baseUrl: ${services.clouddriver.baseUrl}

  orca:
    host: ${services.default.host}
    port: 8083
    baseUrl: ${services.default.protocol}://${services.orca.host}:${services.orca.port}
    enabled: true

  oort:
    host: ${services.clouddriver.host}
    port: ${services.clouddriver.port}
    baseUrl: ${services.clouddriver.baseUrl}

  rosco:
    host: ${services.default.host}
    port: 8087
    baseUrl: ${services.default.protocol}://${services.rosco.host}:${services.rosco.port}

  rush:
    host: ${services.default.host}
    port: 8085
    baseUrl: ${services.default.protocol}://${services.rush.host}:${services.rush.port}
    primaryAccount: ${services.default.primaryAccountName}

  bakery:
    host: ${services.rosco.host}
    port: ${services.rosco.port}
    baseUrl: ${services.rosco.baseUrl}
    extractBuildDetails: true
    propagateCloudProviderType: true

  docker:
    enabled: false
    baseUrl: # Expected in spinnaker-local.yaml

    # If there are multiple accounts then you will need to list them in
    # rush-local.yml. See the docker.accounts section in config/rush.yml.
    primaryAccount:
      name: ${services.default.primaryAccountName}
      url:  ${services.docker.baseUrl}
      registry: ${services.dockerRegistry.baseUrl}

  dockerRegistry:
    baseUrl: #  Expected in spinnaker-local.yml

  jenkins:
    # The "name" entry is used for the display name when selecting
    # this server.
    #
    # If you have multiple jenkins servers, you will need to list
    # them in an igor-local.yml. See jenkins.masters in config/igor.yml.
    defaultMaster:
      name: Jenkins
      baseUrl:   # Expected in spinnaker-local.yml
      username:  # Expected in spinnaker-local.yml
      password:  # Expected in spinnaker-local.yml

  redis:
    host: ${services.default.host}
    port: 6379
    connection: redis://${services.redis.host}:${services.redis.port}

  cassandra:
    host: ${services.default.host}
    port: 9042
    embedded: false
    cluster: CASS_SPINNAKER


providers:
  google:
    enabled: false
    defaultRegion: us-central1
    defaultZone: us-central1-f
    primaryCredentials:
      name: my-account-name
      project: 
      jsonPath:
    credentials:
      name: ${providers.google.primaryCredentials.name}
      project: ${providers.google.primaryCredentials.project}
      jsonPath: ${providers.google.primaryCredentials.jsonPath}

  aws:
    enabled: false
    simpleDBEnabled: false
    defaultRegion: us-east-1
    defaultSimpleDBDomain: CLOUD_APPLICATIONS
    primaryCredentials:
      name: default
      aws_access_key:
      aws_secret_key: 
